version: "3.8"

services:
  
  php:
    container_name: php-fpm
    build:
      context: .
      dockerfile: php/Dockerfile
    depends_on:
      - mariadb
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/ 
      - ./logs/php.log:/var/log/fpm-php.www.log  
  
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8086:80"
    depends_on:
      - php
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/  

  mariadb:
    image: mariadb
    container_name: mariadb
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password0
      MYSQL_DATABASE: bdd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - mariadb
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password0
    networks:
      - internal

networks:
  internal:

volumes:
  db_data:  